### ISSUE TITLE
non-existence points

### ISSUE THREAD

**Issue by Xunius** [sujithTSR/surface-curvature#1]
Hi,
I was using your code help understand how to compute principal curvatures, and it seems that in your example there are some nan points, stemming from `H**2 - K <0`. Any idea why this happens and how to deal with it?
Thanks

**Comment by Xunius** [comment]
Update myself:

I think you made a typo in the code, at line 70:
```
	K=(L*N-M**2)/(E*G-L**2)
```
should be
```
	K=(L*N-M**2)/(E*G-F**2)
```

and also the mean curvature should be divided by 2:
```
H = (E*N + G*L - 2*F*M)/((E*G - F**2)) / 2.
```

But I got another question, I tried to get the principal curvatures from the eigenvalues of the shape operator, like this:
```
        idx=1
        bb=E[idx]; cc=F[idx]; dd=G[idx]
        ee=L[idx]; ff=M[idx]; gg=N[idx]

        I=np.array([[bb,cc],[cc,dd]])
        II=np.array([[ee,ff],[ff,gg]])
        ss=np.linalg.inv(I)*II

        eig=np.linalg.eig(ss)
```
and the resultant eigenvalues don't match `Pmax[idx]` and `Pmin[idx]`. Did I do something wrong?

Update myself again:
I should have used `np.linalg.inv(I).dot(II)` instead. Now the results are consistent.

**Comment by yoda0612** [comment]
Hello, how should I prepare my data once I have a set of 3D coordination?

**Comment by Xunius** [comment]
@yoda0612 You could try reading the source code `surface.py`, there is an example.

**Comment by sujithTSR** [comment]
> Update myself:
> 
> I think you made a typo in the code, at line 70:
> 
> ```
> 	K=(L*N-M**2)/(E*G-L**2)
> ```
> 
> should be
> 
> ```
> 	K=(L*N-M**2)/(E*G-F**2)
> ```
> 
> and also the mean curvature should be divided by 2:
> 
> ```
> H = (E*N + G*L - 2*F*M)/((E*G - F**2)) / 2.
> ```
> 
> But I got another question, I tried to get the principal curvatures from the eigenvalues of the shape operator, like this:
> 
> ```
>         idx=1
>         bb=E[idx]; cc=F[idx]; dd=G[idx]
>         ee=L[idx]; ff=M[idx]; gg=N[idx]
> 
>         I=np.array([[bb,cc],[cc,dd]])
>         II=np.array([[ee,ff],[ff,gg]])
>         ss=np.linalg.inv(I)*II
> 
>         eig=np.linalg.eig(ss)
> ```
> 
> and the resultant eigenvalues don't match `Pmax[idx]` and `Pmin[idx]`. Did I do something wrong?
> 
> Update myself again:
> I should have used `np.linalg.inv(I).dot(II)` instead. Now the results are consistent.

Hey, 
Thanks for the help. :)

**Comment by sujithTSR** [comment]
- Xunius, 
Thanks for rectifying the mistakes. 
I've made the changes and committed the code. (y) 
Closing the issue as it is now solved!
